#!/usr/bin/env sh
exec guile -L . -s "$0" "$@"
!#

;;; makefile2potato - Convert POSIX Makefiles to potato-make scripts

(use-modules (potato makefile-parser)
             (ice-9 getopt-long))

(define option-spec
  '((help    (single-char #\h) (value #f))
    (output  (single-char #\o) (value #t))))

(define (display-help)
  (display "makefile2potato - Convert POSIX Makefiles to potato-make scripts\n\n")
  (display "Usage: makefile2potato [OPTIONS] MAKEFILE\n\n")
  (display "Options:\n")
  (display "  -h, --help              Display this help message\n")
  (display "  -o, --output=FILE       Write output to FILE (default: stdout)\n\n")
  (display "Example:\n")
  (display "  makefile2potato Makefile > build.scm\n")
  (display "  makefile2potato -o build.scm Makefile\n"))

(define (main args)
  (let* ((options (getopt-long args option-spec))
         (help? (option-ref options 'help #f))
         (output-file (option-ref options 'output #f))
         (rest-args (option-ref options '() '())))
    
    (cond
     ;; Show help
     (help?
      (display-help)
      (exit 0))
     
     ;; No input file specified
     ((null? rest-args)
      (display "Error: No Makefile specified\n" (current-error-port))
      (display "Try 'makefile2potato --help' for more information.\n" (current-error-port))
      (exit 1))
     
     ;; Convert the makefile
     (else
      (let ((input-file (car rest-args)))
        (catch #t
          (lambda ()
            (let ((converted (makefile->potato-make input-file)))
              (if output-file
                  (with-output-to-file output-file
                    (lambda () (display converted)))
                  (display converted))))
          (lambda (key . args)
            (format (current-error-port) "Error: ~a\n" 
                    (if (null? args) key (car args)))
            (exit 1))))))))

(main (command-line))
