(define-module (potato builtins)
  #:export (builtin-makevars))

(define builtin-makevars
  '(("MAKE" . "make")
    ("AR"   . "ar")
    ("ARFLAGS" . "-rv")
    ("YACC" . "yacc")
    ("YFLAGS" . "")
    ("LEX" . "lex")
    ("LFLAGS" . "")
    ("LDFLAGS" . "")
    ("CC" . "cc")
    ("CFLAGS" . "-g -O2")
    ("FC" . "gfortran")
    ("FFLAGS" . "-O1")
    ("GUILE" . "guile")
    ("GUILD" . "guild")
    ("GFLAGS" . "-W2")))
