#!/usr/bin/env sh
exec guile -L . -s "$0" "$@"
!#
(use-modules (potato make)
             (srfi srfi-1)
             (srfi srfi-64))

(test-begin "automatic-variables")

(test-equal "A phony target rule with no prerequisites defines $@."
  #t
  (begin
    (initialize)
    (: "clean" '()
       (lambda ()
         (string=? ($@) "clean")))
    (execute)))

(test-equal "A phony target rule with no prerequisites defines $*."
  #t
  (begin
    (initialize)
    (: "clean" '()
       (lambda ()
         (string=? ($*) "clean")))
    (execute)))

(test-equal "A phony target rule with no prerequisites has empty string $<."
  #t
  (begin
    (initialize)
    (: "clean" '()
       (lambda ()
         (string-null? ($<))))
    (execute)))

(test-equal "A phony target rule with no prerequisites has null list $$?."
  #t
  (begin
    (initialize)
    (: "clean" '()
       (lambda ()
         (null? ($$?))))
    (execute)))

(test-equal "A phony target rule with no prerequisites has empty string $?."
  #t
  (begin
    (initialize)
    (: "clean" '()
       (lambda ()
         (string-null? ($?))))
    (execute)))

(test-equal "A phony target rule with no prerequisites has null list $$^."
  #t
  (begin
    (initialize)
    (: "clean" '()
       (lambda ()
         (null? ($$^))))
    (execute)))

(test-equal "A phony target rule with no prerequisites has empty string $^."
  #t
  (begin
    (initialize)
    (: "clean" '()
       (lambda ()
         (string-null? ($^))))
    (execute)))

;;;;;;;;;;;;;;;;

(test-equal "A target rule with a prerequisite defines $@."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x")
       (lambda ()
         (string=? ($@) "foo.exe")))
    (: "foo.x" '() #t)
    (execute)))

(test-equal "A target rule with a prerequisite defines $*."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x")
       (lambda ()
         (string=? ($*) "foo")))
    (: "foo.x" '() #t)
    (execute)))

(test-equal "A target rule with a prerequisite defines $<."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x")
       (lambda ()
         (string=? ($<) "foo.x")))
    (: "foo.x" '() #t)
    (execute)))

(test-equal "A target rule with a prerequisite defines $$?."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x")
       (lambda ()
         (equal? ($$?) (list "foo.x"))))
    (: "foo.x" '() #t)
    (execute)))

(test-equal "A target rule with a prerequisite defines $?."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x")
       (lambda ()
         (string=? ($?) "foo.x")))
    (: "foo.x" '() #t)
    (execute)))

(test-equal "A target rule with a prerequisite defines $$^."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x")
       (lambda ()
         (equal? ($$?) (list "foo.x"))))
    (: "foo.x" '() #t)
    (execute)))

(test-equal "A target rule with a prerequisite defines $^."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x")
       (lambda ()
         (string=? ($?) "foo.x")))
    (: "foo.x" '() #t)
    (execute)))

;;;;;;;;;;;;;;;;

(test-equal "A target rule with multiple prerequisites defines $@."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x" "foo.y")
       (lambda ()
         (string=? ($@) "foo.exe")))
    (: "foo.x" '() #t)
    (: "foo.y" '() #t)
    (execute)))

(test-equal "A target rule with multiple prerequisites defines $*."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x" "foo.y")
       (lambda ()
         (string=? ($*) "foo")))
    (: "foo.x" '() #t)
    (: "foo.y" '() #t)
    (execute)))

(test-equal "A target rule with multiple prerequisites defines $<."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x" "foo.y")
       (lambda ()
         (string=? ($<) "foo.x")))
    (: "foo.x" '() #t)
    (: "foo.y" '() #t)
    (execute)))

(test-equal "A target rule with multiple prerequisites defines $$?."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x" "foo.y")
       (lambda ()
         (equal? ($$?) (list "foo.x" "foo.y"))))
    (: "foo.x" '() #t)
    (: "foo.y" '() #t)
    (execute)))

(test-equal "A target rule with multiple prerequisites defines $?."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x" "foo.y")
       (lambda ()
         (string=? ($?) "foo.x foo.y")))
    (: "foo.x" '() #t)
    (: "foo.y" '() #t)
    (execute)))

(test-equal "A target rule with multiple prerequisites defines $$^."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x" "foo.y")
       (lambda ()
         (equal? ($$?) (list "foo.x" "foo.y"))))
    (: "foo.x" '() #t)
    (: "foo.y" '() #t)
    (execute)))

(test-equal "A target rule with multiple prerequisites defines $^."
  #t
  (begin
    (initialize)
    (: "foo.exe" '("foo.x" "foo.y")
       (lambda ()
         (string=? ($?) "foo.x foo.y")))
    (: "foo.x" '() #t)
    (: "foo.y" '() #t)
    (execute)))

(test-assert "A target rule includes only newer prerequisites in $? and $$?."
  (let* ((base (number->string (getpid)))
         (target (string-append "pmake-target-" base ".tmp"))
         (older-prereq (string-append "pmake-older-" base ".tmp"))
         (newer-prereq (string-append "pmake-newer-" base ".tmp")))
    (for-each
     (lambda (f)
       (false-if-exception (delete-file f)))
     (list target older-prereq newer-prereq))

    (call-with-output-file older-prereq (lambda (p) (display "older" p)))
    (call-with-output-file target (lambda (p) (display "target" p)))
    (call-with-output-file newer-prereq (lambda (p) (display "newer" p)))

    ;; Ensure deterministic order: older-prereq < target < newer-prereq
    (system (string-append "touch -t 202401010101.01 " older-prereq))
    (system (string-append "touch -t 202401010102.01 " target))
    (system (string-append "touch -t 202401010103.01 " newer-prereq))

    (let ((ok
           (begin
             (initialize '("test"))
             (: target (list older-prereq newer-prereq)
                (lambda ()
                  (and (equal? ($$?) (list newer-prereq))
                       (string=? ($?) newer-prereq))))
             (execute #:targets (list target)))))
      (for-each
       (lambda (f)
         (false-if-exception (delete-file f)))
       (list target older-prereq newer-prereq))
      ok)))

;;;;;;;;;;;;;;;;

(test-equal "A suffix rule with a prerequisite defines $@."
  #t
  (begin
    (initialize '("test" "foo.y"))
    (-> ".x" ".y"
        (lambda ()
          (format #t "BLAMMO ~A~%" ($@))
          (string=? ($@) "foo.y")))
    (: "foo.x" '() #t)
    (execute)))

(test-equal "A suffix rule with a prerequisite defines $*."
  #t
  (begin
    (initialize '("test" "foo.y"))
    (-> ".x" ".y"
        (lambda ()
          (format #t "BLAMMO ~A~%" ($*))
          (string=? ($*) "foo")))
    (: "foo.x" '() #t)
    (execute)))

(test-equal "A suffix rule with a prerequisite defines $<."
  #t
  (begin
    (initialize '("test" "foo.y"))
    (-> ".x" ".y"
        (lambda ()
          (format #t "BLAMMO ~A~%" ($<))
          (string=? ($<) "foo.x")))
    (: "foo.x" '() #t)
    (execute)))

(test-equal "A suffix rule with a prerequisite defines $$^."
  #t
  (begin
    (initialize '("test" "foo.y"))
    (-> ".x" ".y"
        (lambda ()
          (format #t "BLAMMO ~A~%" ($$^))
          (equal? ($$^) (list "foo.x"))))
    (: "foo.x" '() #t)
    (execute)))

(test-equal "A suffix rule with a prerequisite defines $^."
  #t
  (begin
    (initialize '("test" "foo.y"))
    (-> ".x" ".y"
        (lambda ()
          (format #t "BLAMMO ~A~%" ($^))
          (equal? ($^) "foo.x")))
    (: "foo.x" '() #t)
    (execute)))

(test-end "automatic-variables")

;; Local Variables:
;; mode: scheme
;; End:
