#!/usr/bin/env sh
exec guile -L . -s "$0" "$@"
!#
(use-modules (potato makefile-parser)
             (srfi srfi-64)
             (ice-9 textual-ports))

(test-begin "special-targets")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Test .POSIX special target

(test-assert ".POSIX as first non-comment line is accepted"
  (let ((output (makefile->potato-make "tests/special-posix.mk")))
    (and (string? output)
         (not (string-contains output "(: \".POSIX\"")))))  ;; Should not have a .POSIX target rule

(test-error ".POSIX not as first non-comment line should error"
  #t
  (makefile->potato-make "tests/special-posix-error.mk"))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Test .PHONY special target

(test-assert ".PHONY targets are marked with comments"
  (let ((output (makefile->potato-make "tests/special-phony.mk")))
    (and (string-contains output ";; all is a phony target")
         (string-contains output ";; clean is a phony target")
         (string-contains output ";; install is a phony target")
         (string-contains output ";; test is a phony target")
         (not (string-contains output "(: \".PHONY\"")))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Test .IGNORE special target

(test-assert ".IGNORE targets use ~~- for error ignoring"
  (let ((output (makefile->potato-make "tests/special-ignore.mk")))
    (and (string-contains output "(~~- \"rm -f prog main.o\")")
         (string-contains output ";; clean ignores command errors")
         (string-contains output ";; distclean ignores command errors")
         (not (string-contains output "(: \".IGNORE\"")))))

(test-assert ".IGNORE with no prerequisites makes all targets ignore errors"
  (let ((output (makefile->potato-make "tests/special-ignore.mk")))
    ;; After empty .IGNORE, the 'test' target should also use ~~-
    (and (string-contains output ";; test ignores command errors")
         (string-contains output "(~~- \"false\")")
         (string-contains output "(~~- \"echo"))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Test .DEFAULT special target

(test-assert ".DEFAULT rule is documented in comments"
  (let ((output (makefile->potato-make "tests/special-default.mk")))
    (and (string-contains output ";; .DEFAULT rule for targets without other rules")
         (string-contains output ";; In .DEFAULT, $< evaluates to the current target name")
         (string-contains output ";; DEFAULT RECIPE:")
         (not (string-contains output "(: \".DEFAULT\"")))))

(test-error ".DEFAULT with prerequisites should error"
  #t
  (makefile->potato-make "tests/special-default-error.mk"))

(test-error ".DEFAULT without commands should error"
  #t
  (makefile->potato-make "tests/special-default-error2.mk"))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(test-end "special-targets")

;; Local Variables:
;; mode: scheme
;; End:
