#!/usr/bin/env sh
exec guile -L . -s "$0" "$@"
!#

(use-modules (potato make)
             (srfi srfi-1)
             (srfi srfi-64))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; TARGET RULES

(test-begin "target_rules")

;; These stubs override the driver that calls
;; 'system' so we can instead just investigate
;; what string it was passed.
(define %cmd #f)
(define (stub-system-pass cmd)
  (format #t "stub-system-pass receive command ~S~%" cmd)
  (set! %cmd cmd)
  0)
(define (stub-system-fail cmd)
  (set! %cmd cmd)
  1)


(test-assert "Install alternate system driver."
  (false-if-exception (install-alternate-system-driver stub-system-pass)))

(test-equal "A string target rule is sent to system driver."
  "cc -o foo.exe foo.c"
  (begin
    (initialize)
    (: "foo.exe" '("foo.c")
       "cc -o foo.exe foo.c")
    (: "foo.c" '() #t)
    (execute)
    %cmd))

(test-assert "target rule is a procedure"
  (begin
    (let ((tmpvar #f))
      (initialize '("test" "foo.exe"))
      (: "foo.exe" '("foo.c")
         (lambda ()
           (set! tmpvar #t)))
      (: "foo.c" '() #t)
      (execute)
      tmpvar)))

(test-equal "target rule is a procedure returning a string"
  "cc -o foo.exe foo.c"
  (begin
    (initialize '("test" "foo.exe"))
    (: "foo.exe" '("foo.c")
       (lambda ()
         ("cc -o foo.exe foo.c")))
    (execute)
    %cmd))

(test-equal "target rule using string-compose on a string"
  "cc -o foo.exe foo.c"
  (begin
    (initialize '("test" "foo.exe"))
    (: "foo.exe" '("foo.c")
       (~ "cc -o foo.exe foo.c"))
    (execute)
    %cmd))

(test-equal "target rule using string-compose on special variables"
  "cc -o foo.exe foo.c"
  (begin
    (initialize '("test" "foo.exe"))
    (: "foo.exe" '("foo.c")
       (~ "cc -o" $@ $<))
    (execute)
    %cmd))

(test-equal "target rule check success"
  #t
  (begin
    (initialize '("test" "foo.exe"))
    (: "foo.exe" '("foo.c")
       (~ "cc -o" $@ $<))
    (: "foo.c" '() #t)
    (execute)))

(test-assert "install failing alternate system driver"
  (false-if-exception (install-alternate-system-driver stub-system-fail)))

;; Non-nominal: with a failing system driver and no ignore option,
;; execute should fail the target.
(test-equal "target rule check failure of system call"
  #f
  (begin
    (initialize '("test" "foo.exe"))
    (: "foo.exe" '("foo.c")
       (~ "cc -o" $@ $<))
    (execute)))

;; Non-nominal: a recipe procedure that returns #f is treated as failure.
(test-equal "target rule check failure of scheme procedure"
  #f
  (begin
    (initialize '("test" "foo.exe"))
    (: "foo.exe" '("foo.c")
       (lambda ()
         #f))
    (execute)))

;; Non-nominal: first recipe fails, but per-recipe ignore (~-) should
;; allow the next recipe to run and the overall target to pass.
(test-assert "ignore-error recipe option is honored and execution continues"
  (let ((continued? #f))
    (initialize '("test" "foo.exe"))
    (: "foo.exe" '("foo.c")
       (~- "cc -o" $@ $<)
       (lambda ()
         (set! continued? #t)
         #t))
    (: "foo.c" '() #t)
    (and (execute)
         continued?)))

;; Non-nominal: global --ignore-errors should have the same effect even
;; when the failing recipe does not use the per-recipe ignore marker.
(test-assert "--ignore-errors is honored and execution continues"
  (let ((continued? #f))
    (initialize '("test" "--ignore-errors" "foo.exe"))
    (: "foo.exe" '("foo.c")
       (~ "cc -o" $@ $<)
       (lambda ()
         (set! continued? #t)
         #t))
    (: "foo.c" '() #t)
    (and (execute)
         continued?)))

(test-end "target_rules")
